name: netlify-cache
description: >-
  Nuxt module that uses netlify cache to speed up redeploy for Nuxt version <
  2.14
repo: DreaMinder/nuxt-netlify-cache
npm: nuxt-netlify-cache
icon: netlify.png
github: https://github.com/DreaMinder/nuxt-netlify-cache
website: https://github.com/DreaMinder/nuxt-netlify-cache
learn_more: https://www.netlify.com/
category: Deployment
type: 3rd-party
maintainers:
  - name: DreaMinder
    github: DreaMinder
compatibility:
  nuxt: ^2.0.0
  requires: {}
