name: netlify
description: Local emulation of the Netlify platform in development
repo: netlify/primitives#main/packages/nuxt-module
npm: '@netlify/nuxt'
icon: netlify.svg
github: https://github.com/netlify/primitives
website: https://github.com/netlify/primitives#readme
learn_more: https://npmx.dev/package/@netlify/nuxt
category: Deployment
type: 3rd-party
maintainers:
  - name: Netlify
    github: netlify
compatibility:
  nuxt: ^3.0.0 || ^4.0.0
  requires: {}
