name: nuxt-safe-runtime-config
description: Validate Nuxt runtime config with Standard Schema at build time
repo: onmax/nuxt-safe-runtime-config#main
npm: nuxt-safe-runtime-config
icon: nuxt-safe-runtime-config.svg
github: https://github.com/onmax/nuxt-safe-runtime-config/tree/main
website: https://github.com/onmax/nuxt-safe-runtime-config/tree/main
learn_more: ''
category: Devtools
type: 3rd-party
maintainers:
  - name: Max
    github: onmax
    bluesky: onmax.bsky.social
    twitter: _onmax
compatibility:
  nuxt: ^3.0.0
  requires: {}
