name: Module Request
description: Request to add a new module to the overview
title: "[Module Request]: `...`"
labels: ["module-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this module request!
  - type: textarea
    id: features
    attributes:
      label: Features
      description: Explain in a few sentences what your module does.
      placeholder: This module is a wrapper for...
    validations:
      required: true
  - type: input
    id: repository
    attributes:
      label: Repository
      description: Drop a link to the source repository.
      placeholder: https://github.com/...
    validations:
      required: true
  - type: dropdown
    id: compatibility
    attributes:
      label: Nuxt Compatibility
      description: What version of Nuxt is the module compatible with?
      multiple: true
      options:
        - Nuxt 2
        - Nuxt Bridge
        - Nuxt 3
    validations:
      required: true
