name: release

on:
  push:
    branches:
      - main
    paths: 
      - 'modules/**'
      - 'lib/**'
      - '.github/workflows/release.yml'

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: latest
          cache: "pnpm"
      - run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm release
